/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import MAIN.SinhVien;
import MAIN.Diem;
import MAIN.Lop;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Menu extends javax.swing.JFrame {

    int x = 210;    //chieu rong
    int y = 600;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        HOMEPAGE.setVisible(true);
        ACCOUNTMANAGE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        Slide_menu.setSize(210,600);
        
        loadTableData_Student();
        loadTableData_Class();
        loadTableData_Grade();
    }

    // Trong Menu.java hoặc lớp giao diện chính


    public void openMenu() {
        Slide_menu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 210; i++) {
                            Slide_menu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 210;
        }
    }

    public void closeMenu() {
        Slide_menu.setSize(x, y);
        if (x == 210) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 210; i >= 0; i--) {
                            Slide_menu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTotal = new javax.swing.JPanel();
        Tittle_font = new javax.swing.JPanel();
        Slide_menu = new javax.swing.JPanel();
        Include_icon = new javax.swing.JPanel();
        Closemenu = new javax.swing.JLabel();
        Icon_app = new javax.swing.JLabel();
        HOMEPAGE_menuslide = new javax.swing.JLabel();
        STUDENMANAGE_menuslide = new javax.swing.JLabel();
        LOGOUT_menuslide = new javax.swing.JLabel();
        CLASSMANAGE_menuslide = new javax.swing.JLabel();
        GRADEMANAGE_menuslide = new javax.swing.JLabel();
        CLASSFICATION_menuslide1 = new javax.swing.JLabel();
        Separator_Menuslide = new javax.swing.JSeparator();
        MenuBar = new javax.swing.JPanel();
        OpenMenuicon = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        HOMEPAGE = new javax.swing.JPanel();
        Homepage_tittle = new javax.swing.JLabel();
        ACCOUNTMANAGE = new javax.swing.JPanel();
        Account_tittle = new javax.swing.JLabel();
        MASV = new javax.swing.JLabel();
        HOTEN = new javax.swing.JLabel();
        NGAYSINH = new javax.swing.JLabel();
        DIACHI = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        MALOP = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaLop = new javax.swing.JTextField();
        Add_Student = new javax.swing.JButton();
        Delete_Student = new javax.swing.JButton();
        Update_Student = new javax.swing.JButton();
        Search_Student = new javax.swing.JButton();
        ScrollSinhVien = new javax.swing.JScrollPane();
        BangSinhVien = new javax.swing.JTable();
        CLASSMANAGE = new javax.swing.JPanel();
        CLASSMANAGE_tittle = new javax.swing.JLabel();
        MALOPFK = new javax.swing.JLabel();
        KHOA = new javax.swing.JLabel();
        TENLOP = new javax.swing.JLabel();
        CHUYENNGANH = new javax.swing.JLabel();
        txtMaLopFK = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtTenLop = new javax.swing.JTextField();
        txtChuyenNganh = new javax.swing.JTextField();
        Add_Class = new javax.swing.JButton();
        Delete_Class = new javax.swing.JButton();
        Update_Class = new javax.swing.JButton();
        Search_Class = new javax.swing.JButton();
        SCROLLLOP = new javax.swing.JScrollPane();
        BANGLOP = new javax.swing.JTable();
        GRADEMANAGE = new javax.swing.JPanel();
        GRADEMANAGE_tittle = new javax.swing.JLabel();
        MONHOC = new javax.swing.JLabel();
        DIEM = new javax.swing.JLabel();
        TINCHI = new javax.swing.JLabel();
        MaSVFK = new javax.swing.JLabel();
        txtMonHoc = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtTinChi = new javax.swing.JTextField();
        txtMaSVFK = new javax.swing.JTextField();
        Add_Grade = new javax.swing.JButton();
        Delete_Grade = new javax.swing.JButton();
        Update_Grade = new javax.swing.JButton();
        Search_Grade = new javax.swing.JButton();
        SCROLLDIEM = new javax.swing.JScrollPane();
        BANGDIEM = new javax.swing.JTable();
        CLASSFICATION = new javax.swing.JPanel();
        Classfication_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelTotal.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tittle_font.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout Tittle_fontLayout = new javax.swing.GroupLayout(Tittle_font);
        Tittle_font.setLayout(Tittle_fontLayout);
        Tittle_fontLayout.setHorizontalGroup(
            Tittle_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        Tittle_fontLayout.setVerticalGroup(
            Tittle_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelTotal.add(Tittle_font, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        Slide_menu.setBackground(new java.awt.Color(0, 102, 102));
        Slide_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Slide_menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Slide_menu.setPreferredSize(new java.awt.Dimension(190, 590));
        Slide_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Include_icon.setBackground(new java.awt.Color(255, 255, 255));
        Include_icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Closemenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Closemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closemenu.setText("X");
        Closemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosemenuMouseClicked(evt);
            }
        });

        Icon_app.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/scholar.png"))); // NOI18N

        javax.swing.GroupLayout Include_iconLayout = new javax.swing.GroupLayout(Include_icon);
        Include_icon.setLayout(Include_iconLayout);
        Include_iconLayout.setHorizontalGroup(
            Include_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Include_iconLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Closemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Include_iconLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Icon_app)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Include_iconLayout.setVerticalGroup(
            Include_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Include_iconLayout.createSequentialGroup()
                .addComponent(Closemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icon_app)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Slide_menu.add(Include_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        HOMEPAGE_menuslide.setBackground(new java.awt.Color(255, 255, 255));
        HOMEPAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HOMEPAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        HOMEPAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOMEPAGE_menuslide.setText("Trang Chủ");
        HOMEPAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEPAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(HOMEPAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 30));

        STUDENMANAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        STUDENMANAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        STUDENMANAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        STUDENMANAGE_menuslide.setText("Quản lý sinh viên");
        STUDENMANAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STUDENMANAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(STUDENMANAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 30));

        LOGOUT_menuslide.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LOGOUT_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUT_menuslide.setText("Đăng Xuất");
        Slide_menu.add(LOGOUT_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 210, 30));

        CLASSMANAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLASSMANAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        CLASSMANAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLASSMANAGE_menuslide.setText("Quản lý lớp");
        CLASSMANAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLASSMANAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(CLASSMANAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 30));

        GRADEMANAGE_menuslide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRADEMANAGE_menuslide.setForeground(new java.awt.Color(255, 255, 255));
        GRADEMANAGE_menuslide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRADEMANAGE_menuslide.setText("Quản lý điểm");
        GRADEMANAGE_menuslide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRADEMANAGE_menuslideMouseClicked(evt);
            }
        });
        Slide_menu.add(GRADEMANAGE_menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 30));

        CLASSFICATION_menuslide1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLASSFICATION_menuslide1.setForeground(new java.awt.Color(255, 255, 255));
        CLASSFICATION_menuslide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLASSFICATION_menuslide1.setText("Phân Loại");
        CLASSFICATION_menuslide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLASSFICATION_menuslide1MouseClicked(evt);
            }
        });
        Slide_menu.add(CLASSFICATION_menuslide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 30));
        Slide_menu.add(Separator_Menuslide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 10));

        PanelTotal.add(Slide_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 0, -1));

        MenuBar.setBackground(new java.awt.Color(255, 255, 255));

        OpenMenuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/menu.png"))); // NOI18N
        OpenMenuicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMenuiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(OpenMenuicon)
                .addContainerGap(884, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenMenuicon)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelTotal.add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 940, 60));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new java.awt.CardLayout());

        HOMEPAGE.setBackground(new java.awt.Color(255, 255, 255));

        Homepage_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Homepage_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Homepage_tittle.setText("TRANG CHỦ");

        javax.swing.GroupLayout HOMEPAGELayout = new javax.swing.GroupLayout(HOMEPAGE);
        HOMEPAGE.setLayout(HOMEPAGELayout);
        HOMEPAGELayout.setHorizontalGroup(
            HOMEPAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPAGELayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(Homepage_tittle)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        HOMEPAGELayout.setVerticalGroup(
            HOMEPAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPAGELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Homepage_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        Main.add(HOMEPAGE, "card2");

        ACCOUNTMANAGE.setBackground(new java.awt.Color(255, 255, 255));
        ACCOUNTMANAGE.setMaximumSize(new java.awt.Dimension(937, 540));
        ACCOUNTMANAGE.setMinimumSize(new java.awt.Dimension(937, 540));
        ACCOUNTMANAGE.setPreferredSize(new java.awt.Dimension(937, 540));

        Account_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Account_tittle.setForeground(new java.awt.Color(0, 102, 102));
        Account_tittle.setText("Quản lý sinh viên");

        MASV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MASV.setForeground(new java.awt.Color(0, 102, 102));
        MASV.setText("Mã SV");

        HOTEN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        HOTEN.setForeground(new java.awt.Color(0, 102, 102));
        HOTEN.setText("Họ Tên");

        NGAYSINH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NGAYSINH.setForeground(new java.awt.Color(0, 102, 102));
        NGAYSINH.setText("Ngày Sinh");

        DIACHI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DIACHI.setForeground(new java.awt.Color(0, 102, 102));
        DIACHI.setText("Địa Chỉ");

        EMAIL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EMAIL.setForeground(new java.awt.Color(0, 102, 102));
        EMAIL.setText("Email");

        MALOP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MALOP.setForeground(new java.awt.Color(0, 102, 102));
        MALOP.setText("Mã Lớp");

        txtHoTen.setMaximumSize(new java.awt.Dimension(100, 20));
        txtHoTen.setMinimumSize(new java.awt.Dimension(100, 20));
        txtHoTen.setPreferredSize(new java.awt.Dimension(100, 20));

        txtNgaySinh.setMaximumSize(new java.awt.Dimension(100, 20));
        txtNgaySinh.setMinimumSize(new java.awt.Dimension(100, 20));
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(100, 20));

        txtDiaChi.setMaximumSize(new java.awt.Dimension(100, 20));
        txtDiaChi.setMinimumSize(new java.awt.Dimension(100, 20));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(100, 20));

        txtEmail.setMaximumSize(new java.awt.Dimension(100, 20));
        txtEmail.setMinimumSize(new java.awt.Dimension(100, 20));
        txtEmail.setPreferredSize(new java.awt.Dimension(100, 20));

        txtMaLop.setMaximumSize(new java.awt.Dimension(100, 20));
        txtMaLop.setMinimumSize(new java.awt.Dimension(100, 20));
        txtMaLop.setPreferredSize(new java.awt.Dimension(100, 20));

        Add_Student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add_Student.setForeground(new java.awt.Color(0, 102, 102));
        Add_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/add.png"))); // NOI18N
        Add_Student.setText("Lưu");
        Add_Student.setToolTipText("Lưu thông tin sinh viên");
        Add_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_StudentMouseClicked(evt);
            }
        });

        Delete_Student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete_Student.setForeground(new java.awt.Color(0, 102, 102));
        Delete_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/delete.png"))); // NOI18N
        Delete_Student.setText("Xoá");
        Delete_Student.setToolTipText("Xóa thông tin sinh viên");
        Delete_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_StudentMouseClicked(evt);
            }
        });

        Update_Student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update_Student.setForeground(new java.awt.Color(0, 102, 102));
        Update_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/edit.png"))); // NOI18N
        Update_Student.setText("Sửa");
        Update_Student.setToolTipText("Sửa/Cập nhật thông tin sinh viên");
        Update_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_StudentMouseClicked(evt);
            }
        });

        Search_Student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search_Student.setForeground(new java.awt.Color(0, 102, 102));
        Search_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/search.png"))); // NOI18N
        Search_Student.setText("Tìm");
        Search_Student.setToolTipText("Tìm sinh viên");
        Search_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_StudentMouseClicked(evt);
            }
        });

        BangSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Họ Tên", "Ngày Sinh", "Địa Chỉ", "Email", "Mã Lớp"
            }
        ));
        BangSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangSinhVienMouseClicked(evt);
            }
        });
        ScrollSinhVien.setViewportView(BangSinhVien);

        javax.swing.GroupLayout ACCOUNTMANAGELayout = new javax.swing.GroupLayout(ACCOUNTMANAGE);
        ACCOUNTMANAGE.setLayout(ACCOUNTMANAGELayout);
        ACCOUNTMANAGELayout.setHorizontalGroup(
            ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ScrollSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MASV))
                                .addGap(117, 117, 117)
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NGAYSINH)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)
                                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MALOP)))))
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(Account_tittle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ACCOUNTMANAGELayout.setVerticalGroup(
            ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ACCOUNTMANAGELayout.createSequentialGroup()
                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Add_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Delete_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Update_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Search_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ACCOUNTMANAGELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Account_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScrollSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NGAYSINH)
                            .addComponent(EMAIL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MASV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MALOP)
                            .addComponent(DIACHI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ACCOUNTMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ACCOUNTMANAGELayout.createSequentialGroup()
                        .addComponent(HOTEN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtMaLop.getAccessibleContext().setAccessibleName("");

        Main.add(ACCOUNTMANAGE, "card3");

        CLASSMANAGE.setBackground(new java.awt.Color(255, 255, 255));
        CLASSMANAGE.setMaximumSize(new java.awt.Dimension(937, 540));
        CLASSMANAGE.setMinimumSize(new java.awt.Dimension(937, 540));

        CLASSMANAGE_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CLASSMANAGE_tittle.setForeground(new java.awt.Color(0, 102, 102));
        CLASSMANAGE_tittle.setText("Quản lý lớp");

        MALOPFK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MALOPFK.setForeground(new java.awt.Color(0, 102, 102));
        MALOPFK.setText("Mã Lớp");

        KHOA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        KHOA.setForeground(new java.awt.Color(0, 102, 102));
        KHOA.setText("Khoa");

        TENLOP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TENLOP.setForeground(new java.awt.Color(0, 102, 102));
        TENLOP.setText("Tên Lớp");

        CHUYENNGANH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CHUYENNGANH.setForeground(new java.awt.Color(0, 102, 102));
        CHUYENNGANH.setText("Chuyên Ngành");

        txtKhoa.setMaximumSize(new java.awt.Dimension(100, 20));
        txtKhoa.setMinimumSize(new java.awt.Dimension(100, 20));
        txtKhoa.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTenLop.setMaximumSize(new java.awt.Dimension(100, 20));
        txtTenLop.setMinimumSize(new java.awt.Dimension(100, 20));
        txtTenLop.setPreferredSize(new java.awt.Dimension(100, 20));

        txtChuyenNganh.setMaximumSize(new java.awt.Dimension(100, 20));
        txtChuyenNganh.setMinimumSize(new java.awt.Dimension(100, 20));
        txtChuyenNganh.setPreferredSize(new java.awt.Dimension(100, 20));

        Add_Class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add_Class.setForeground(new java.awt.Color(0, 102, 102));
        Add_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/add.png"))); // NOI18N
        Add_Class.setText("Lưu");
        Add_Class.setToolTipText("Lưu thông tin sinh viên");
        Add_Class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_ClassMouseClicked(evt);
            }
        });

        Delete_Class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete_Class.setForeground(new java.awt.Color(0, 102, 102));
        Delete_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/delete.png"))); // NOI18N
        Delete_Class.setText("Xoá");
        Delete_Class.setToolTipText("Xóa thông tin sinh viên");
        Delete_Class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_ClassMouseClicked(evt);
            }
        });

        Update_Class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update_Class.setForeground(new java.awt.Color(0, 102, 102));
        Update_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/edit.png"))); // NOI18N
        Update_Class.setText("Sửa");
        Update_Class.setToolTipText("Sửa/Cập nhật thông tin sinh viên");
        Update_Class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_ClassMouseClicked(evt);
            }
        });

        Search_Class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search_Class.setForeground(new java.awt.Color(0, 102, 102));
        Search_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/search.png"))); // NOI18N
        Search_Class.setText("Tìm");
        Search_Class.setToolTipText("Tìm sinh viên");
        Search_Class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_ClassMouseClicked(evt);
            }
        });

        BANGLOP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Lớp", "Tên Lớp", "Khoa", "Chuyên Ngành"
            }
        ));
        BANGLOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BANGLOPMouseClicked(evt);
            }
        });
        SCROLLLOP.setViewportView(BANGLOP);

        javax.swing.GroupLayout CLASSMANAGELayout = new javax.swing.GroupLayout(CLASSMANAGE);
        CLASSMANAGE.setLayout(CLASSMANAGELayout);
        CLASSMANAGELayout.setHorizontalGroup(
            CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSMANAGELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SCROLLLOP, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLASSMANAGELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CLASSMANAGE_tittle)
                .addGap(409, 409, 409))
            .addGroup(CLASSMANAGELayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLopFK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MALOPFK))
                        .addGap(150, 150, 150)
                        .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TENLOP)
                            .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KHOA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CHUYENNGANH))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CLASSMANAGELayout.setVerticalGroup(
            CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLASSMANAGELayout.createSequentialGroup()
                .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Add_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Delete_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Update_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLASSMANAGELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CLASSMANAGE_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SCROLLLOP, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(TENLOP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MALOPFK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaLopFK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CLASSMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addComponent(CHUYENNGANH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CLASSMANAGELayout.createSequentialGroup()
                        .addComponent(KHOA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Main.add(CLASSMANAGE, "card3");

        GRADEMANAGE.setBackground(new java.awt.Color(255, 255, 255));
        GRADEMANAGE.setMaximumSize(new java.awt.Dimension(937, 540));
        GRADEMANAGE.setMinimumSize(new java.awt.Dimension(937, 540));

        GRADEMANAGE_tittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GRADEMANAGE_tittle.setForeground(new java.awt.Color(0, 102, 102));
        GRADEMANAGE_tittle.setText("Quản lý điểm");

        MONHOC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MONHOC.setForeground(new java.awt.Color(0, 102, 102));
        MONHOC.setText("Môn học");

        DIEM.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DIEM.setForeground(new java.awt.Color(0, 102, 102));
        DIEM.setText("Điểm");

        TINCHI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TINCHI.setForeground(new java.awt.Color(0, 102, 102));
        TINCHI.setText("Tín Chỉ");

        MaSVFK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaSVFK.setForeground(new java.awt.Color(0, 102, 102));
        MaSVFK.setText("Mã SV");

        txtDiem.setMaximumSize(new java.awt.Dimension(100, 20));
        txtDiem.setMinimumSize(new java.awt.Dimension(100, 20));
        txtDiem.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTinChi.setMaximumSize(new java.awt.Dimension(100, 20));
        txtTinChi.setMinimumSize(new java.awt.Dimension(100, 20));
        txtTinChi.setPreferredSize(new java.awt.Dimension(100, 20));

        txtMaSVFK.setMaximumSize(new java.awt.Dimension(100, 20));
        txtMaSVFK.setMinimumSize(new java.awt.Dimension(100, 20));
        txtMaSVFK.setPreferredSize(new java.awt.Dimension(100, 20));

        Add_Grade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add_Grade.setForeground(new java.awt.Color(0, 102, 102));
        Add_Grade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/add.png"))); // NOI18N
        Add_Grade.setText("Lưu");
        Add_Grade.setToolTipText("Lưu thông tin sinh viên");
        Add_Grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_GradeMouseClicked(evt);
            }
        });

        Delete_Grade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete_Grade.setForeground(new java.awt.Color(0, 102, 102));
        Delete_Grade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/delete.png"))); // NOI18N
        Delete_Grade.setText("Xoá");
        Delete_Grade.setToolTipText("Xóa thông tin sinh viên");
        Delete_Grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_GradeMouseClicked(evt);
            }
        });

        Update_Grade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update_Grade.setForeground(new java.awt.Color(0, 102, 102));
        Update_Grade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/edit.png"))); // NOI18N
        Update_Grade.setText("Sửa");
        Update_Grade.setToolTipText("Sửa/Cập nhật thông tin sinh viên");
        Update_Grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_GradeMouseClicked(evt);
            }
        });

        Search_Grade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search_Grade.setForeground(new java.awt.Color(0, 102, 102));
        Search_Grade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/For_Login/For_Home/search.png"))); // NOI18N
        Search_Grade.setText("Tìm");
        Search_Grade.setToolTipText("Tìm sinh viên");
        Search_Grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_GradeMouseClicked(evt);
            }
        });

        BANGDIEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Môn Học", "Số Tín Chỉ", "Điểm", "Mã SV"
            }
        ));
        BANGDIEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BANGDIEMMouseClicked(evt);
            }
        });
        SCROLLDIEM.setViewportView(BANGDIEM);

        javax.swing.GroupLayout GRADEMANAGELayout = new javax.swing.GroupLayout(GRADEMANAGE);
        GRADEMANAGE.setLayout(GRADEMANAGELayout);
        GRADEMANAGELayout.setHorizontalGroup(
            GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GRADEMANAGELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SCROLLDIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GRADEMANAGELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GRADEMANAGE_tittle)
                .addGap(409, 409, 409))
            .addGroup(GRADEMANAGELayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MONHOC))
                        .addGap(150, 150, 150)
                        .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TINCHI)
                            .addComponent(txtTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSVFK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaSVFK))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GRADEMANAGELayout.setVerticalGroup(
            GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GRADEMANAGELayout.createSequentialGroup()
                .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Add_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Delete_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Update_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Search_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GRADEMANAGELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GRADEMANAGE_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SCROLLDIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(TINCHI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MONHOC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(GRADEMANAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addComponent(MaSVFK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSVFK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GRADEMANAGELayout.createSequentialGroup()
                        .addComponent(DIEM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Main.add(GRADEMANAGE, "card3");

        CLASSFICATION.setBackground(new java.awt.Color(255, 255, 255));

        Classfication_title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Classfication_title.setForeground(new java.awt.Color(0, 102, 102));
        Classfication_title.setText("PHÂN LOẠI");

        javax.swing.GroupLayout CLASSFICATIONLayout = new javax.swing.GroupLayout(CLASSFICATION);
        CLASSFICATION.setLayout(CLASSFICATIONLayout);
        CLASSFICATIONLayout.setHorizontalGroup(
            CLASSFICATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSFICATIONLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(Classfication_title)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        CLASSFICATIONLayout.setVerticalGroup(
            CLASSFICATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSFICATIONLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Classfication_title)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        Main.add(CLASSFICATION, "card5");

        PanelTotal.add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 940, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClosemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosemenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_ClosemenuMouseClicked
        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Slide_menu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void HOMEPAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEPAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(true);
        ACCOUNTMANAGE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_HOMEPAGE_menuslideMouseClicked

    private void STUDENMANAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STUDENMANAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTMANAGE.setVisible(true);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        closeMenu();
    }//GEN-LAST:event_STUDENMANAGE_menuslideMouseClicked

    private void OpenMenuiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMenuiconMouseClicked
        openMenu();
    }//GEN-LAST:event_OpenMenuiconMouseClicked

    private void CLASSMANAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLASSMANAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTMANAGE.setVisible(false);
        CLASSMANAGE.setVisible(true);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(false);
        loadTableData_Class();
        closeMenu();
    }//GEN-LAST:event_CLASSMANAGE_menuslideMouseClicked

    private void CLASSFICATION_menuslide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLASSFICATION_menuslide1MouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTMANAGE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(false);
        CLASSFICATION.setVisible(true);
        closeMenu();
    }//GEN-LAST:event_CLASSFICATION_menuslide1MouseClicked

    private void GRADEMANAGE_menuslideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRADEMANAGE_menuslideMouseClicked
        HOMEPAGE.setVisible(false);
        ACCOUNTMANAGE.setVisible(false);
        CLASSMANAGE.setVisible(false);
        GRADEMANAGE.setVisible(true);
        CLASSFICATION.setVisible(false);
        loadTableData_Grade();
        closeMenu();
    }//GEN-LAST:event_GRADEMANAGE_menuslideMouseClicked

    private void Add_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_StudentMouseClicked
        try {
            // check thu cac fields co trong hay khong
            if (txtMaSV.getText().trim().isEmpty() || 
                txtHoTen.getText().trim().isEmpty() || 
                txtNgaySinh.getText().trim().isEmpty() || 
                txtDiaChi.getText().trim().isEmpty() || 
                txtEmail.getText().trim().isEmpty() || 
                txtMaLop.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
               
            // bo sung data vo bang lop va diem
            String diemQuery = "INSERT IGNORE INTO diem (MASV) VALUES (?)";
            PreparedStatement pstDiem = con.prepareStatement(diemQuery);
            pstDiem.setString(1, txtMaSV.getText());
            pstDiem.executeUpdate();

            String malopQuery = "INSERT IGNORE INTO lop (MALOP) VALUES (?)";
            PreparedStatement pstMalop = con.prepareStatement(malopQuery);
            pstMalop.setString(1, txtMaLop.getText());
            pstMalop.executeUpdate();
            
            // add sinh vien
            String query = "INSERT INTO sinhvien (MASV, HOTEN, NGAYSINH, DIACHI, EMAIL, MALOP) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, txtMaSV.getText());
            pst.setString(2, txtHoTen.getText());

            String inputDate = txtNgaySinh.getText();
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                java.util.Date parsedDate = inputFormat.parse(inputDate);
                String formattedDate = dbFormat.format(parsedDate);
                pst.setString(3, formattedDate);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Định dạng phải là dd/MM/yyyy.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            pst.setString(4, txtDiaChi.getText());
            pst.setString(5, txtEmail.getText());
            pst.setString(6, txtMaLop.getText());

            pst.executeUpdate();

            loadTableData_Student();
            clearTxtFields_Student();

            JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            con.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Add_StudentMouseClicked

    private void Delete_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_StudentMouseClicked
        try {
            int selectedRow = BangSinhVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String maSV = BangSinhVien.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Bạn có chắc muốn xóa sinh viên này?? \n (Không thể hoàn tác)", 
                    "Xóa sinh viên", 
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
                
                // xoa tu bang sinhvien
                String deleteSinhVienQuery = "DELETE FROM sinhvien WHERE MASV = ?";
                PreparedStatement pstSinhVien = con.prepareStatement(deleteSinhVienQuery);
                pstSinhVien.setString(1, maSV);
                pstSinhVien.executeUpdate();
                
                // xoa data ben bang diem
                String deleteDiemQuery = "DELETE FROM diem WHERE MASV = ?";
                PreparedStatement pstDiem = con.prepareStatement(deleteDiemQuery);
                pstDiem.setString(1, maSV);
                pstDiem.executeUpdate();

                // xoa data khoi bang lop neu khong co sv nao khac tham chieu cung MALOP
                String checkOtherStudentsQuery = "SELECT COUNT(*) FROM sinhvien WHERE MALOP = (SELECT MALOP FROM sinhvien WHERE MASV = ?)";
                PreparedStatement pstCheck = con.prepareStatement(checkOtherStudentsQuery);
                pstCheck.setString(1, maSV);

                ResultSet rs = pstCheck.executeQuery();
                if (rs.next() && rs.getInt(1) <= 1) { // new chi co 1 hoac k co sv nao tham chieu MALOP
                    String deleteLopQuery = "DELETE FROM lop WHERE MALOP = (SELECT MALOP FROM sinhvien WHERE MASV = ?)";
                    PreparedStatement pstLop = con.prepareStatement(deleteLopQuery);
                    pstLop.setString(1, maSV);
                    pstLop.executeUpdate();
                }

                loadTableData_Student();
                clearTxtFields_Student();

                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                con.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Delete_StudentMouseClicked

    private void Update_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_StudentMouseClicked
        try {
            int selectedRow = BangSinhVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần cập nhật");
                return;
            }
            
            String studentId = (String) BangSinhVien.getValueAt(selectedRow, 0); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

            // bo sung vao bang diem va lop
            String diemQuery = "INSERT IGNORE INTO diem (MASV) VALUES (?)";
            PreparedStatement pstDiem = con.prepareStatement(diemQuery);
            pstDiem.setString(1, studentId);
            pstDiem.executeUpdate();

            String malopQuery = "INSERT IGNORE INTO lop (MALOP) VALUES (?)";
            PreparedStatement pstMalop = con.prepareStatement(malopQuery);
            pstMalop.setString(1, txtMaLop.getText());
            pstMalop.executeUpdate();

            // update sv
            String updateQuery = "UPDATE sinhvien SET HOTEN=?, NGAYSINH=?, DIACHI=?, EMAIL=?, MALOP=? WHERE MASV=?";
            PreparedStatement pstUpdate = con.prepareStatement(updateQuery);

            pstUpdate.setString(1, txtHoTen.getText());

            String inputDate = txtNgaySinh.getText();
            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                java.util.Date parsedDate = inputFormat.parse(inputDate);
                String formattedDate = dbFormat.format(parsedDate);
                pstUpdate.setString(2, formattedDate); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Định dạng phải là dd/MM/yyyy.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            pstUpdate.setString(3, txtDiaChi.getText());
            pstUpdate.setString(4, txtEmail.getText());
            pstUpdate.setString(5, txtMaLop.getText());
            pstUpdate.setString(6, studentId); 

            pstUpdate.executeUpdate();
            loadTableData_Student();

            JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);

            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Update_StudentMouseClicked

    private void Search_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_StudentMouseClicked
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
            String query = "SELECT * FROM sinhvien WHERE MASV LIKE ? OR HOTEN LIKE ? OR MALOP LIKE ?";
            PreparedStatement pst = con.prepareStatement(query);
        
            String searchMaSV = "%" + txtMaSV.getText().trim() + "%";
            String searchHoTen = "%" + txtHoTen.getText().trim() + "%";
            String searchMaLop = "%" + txtMaLop.getText().trim() + "%";
            pst.setString(1, searchMaSV);
            pst.setString(2, searchHoTen);
            pst.setString(3, searchMaLop);
            
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) BangSinhVien.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] row =  new Object[6];
                
                row[0] = rs.getString("MASV");
                row[1] = rs.getString("HOTEN");
                row[2] = rs.getString("NGAYSINH");
                row[3] = rs.getString("DIACHI");
                row[4] = rs.getString("EMAIL");
                row[5] = rs.getString("MALOP");
                
                model.addRow(row);
            }
            con.close();
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_Search_StudentMouseClicked

    private void Add_ClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_ClassMouseClicked
        try {
        // Check if the fields are empty
        if (txtMaLopFK.getText().trim().isEmpty() || 
            txtTenLop.getText().trim().isEmpty() || 
            txtKhoa.getText().trim().isEmpty() || 
            txtChuyenNganh.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        String query = "INSERT INTO lop (MALOP, TENLOP, KHOA, CHUYENNGANH) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);

        pst.setString(1, txtMaLopFK.getText());
        pst.setString(2, txtTenLop.getText());
        pst.setString(3, txtKhoa.getText());
        pst.setString(4, txtChuyenNganh.getText());

        pst.executeUpdate();

        loadTableData_Class();
        clearTxtFields_Class();

        JOptionPane.showMessageDialog(this, "Thêm lớp thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Add_ClassMouseClicked

    private void Delete_ClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_ClassMouseClicked
            try {
        int selectedRow = BANGLOP.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp cần xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String maLop = BANGLOP.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa lớp này? \n (Không thể hoàn tác)", 
                "Xóa lớp", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

            // Delete from table lop
            String deleteLopQuery = "DELETE FROM lop WHERE MALOP = ?";
            PreparedStatement pstLop = con.prepareStatement(deleteLopQuery);
            pstLop.setString(1, maLop);
            pstLop.executeUpdate();

            loadTableData_Class();
            clearTxtFields_Class();

            JOptionPane.showMessageDialog(this, "Xóa lớp thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            con.close();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Delete_ClassMouseClicked

    private void Update_ClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_ClassMouseClicked
         try {
        int selectedRow = BANGLOP.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp cần cập nhật");
            return;
        }

        String maLop = (String) BANGLOP.getValueAt(selectedRow, 0); 
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

        String query = "UPDATE lop SET TENLOP = ?, KHOA = ?, CHUYENNGANH = ? WHERE MALOP = ?";
        PreparedStatement pst = con.prepareStatement(query);

        pst.setString(1, txtTenLop.getText());
        pst.setString(2, txtKhoa.getText());
        pst.setString(3, txtChuyenNganh.getText());
        pst.setString(4, maLop);

        pst.executeUpdate();
        loadTableData_Class();

        JOptionPane.showMessageDialog(this, "Cập nhật lớp thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Update_ClassMouseClicked

    private void Search_ClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_ClassMouseClicked
        try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        String query = "SELECT * FROM lop WHERE TENLOP LIKE ?";
        PreparedStatement pst = con.prepareStatement(query);

        String searchTenLop = "%" + txtTenLop.getText().trim() + "%";
        pst.setString(1, searchTenLop);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) BANGLOP.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            Object[] row =  new Object[4];
            row[0] = rs.getString("MALOP");
            row[1] = rs.getString("TENLOP");
            row[2] = rs.getString("KHOA");
            row[3] = rs.getString("CHUYENNGANH");

            model.addRow(row);
        }
        con.close();
    } catch(SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
    }//GEN-LAST:event_Search_ClassMouseClicked

    private void BangSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangSinhVienMouseClicked
        try {
            int selectedRow = BangSinhVien.getSelectedRow();
            if (selectedRow == -1) {
                return;
            }

            // Get selected student ID
            String studentId = (String) BangSinhVien.getValueAt(selectedRow, 0);
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

            // Get student data
            String query = "SELECT * FROM sinhvien WHERE MASV = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtMaSV.setText(rs.getString("MASV"));
                txtHoTen.setText(rs.getString("HOTEN"));

                // Convert date format from yyyy-MM-dd to dd/MM/yyyy
                String dbDate = rs.getString("NGAYSINH");
                SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat displayFormat = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    Date date = dbFormat.parse(dbDate);
                    txtNgaySinh.setText(displayFormat.format(date));
                } catch (Exception e) {
                    txtNgaySinh.setText(dbDate);
                }

                txtDiaChi.setText(rs.getString("DIACHI"));
                txtEmail.setText(rs.getString("EMAIL"));
                txtMaLop.setText(rs.getString("MALOP"));
            }

            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BangSinhVienMouseClicked

   


    
    private void Add_GradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_GradeMouseClicked
        try {
        // Check if the fields are empty
        if (txtMonHoc.getText().trim().isEmpty() || 
            txtTinChi.getText().trim().isEmpty() || 
            txtDiem.getText().trim().isEmpty() || 
            txtMaSVFK.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        String query = "INSERT INTO diem (MONHOC, TINCHI, DIEM, MASV) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);

        pst.setString(1, txtMonHoc.getText());
        pst.setString(2, txtTinChi.getText());
        pst.setString(3, txtDiem.getText());
        pst.setString(4, txtMaSVFK.getText());

        pst.executeUpdate();

        loadTableData_Grade();
        clearTxtFields_Grade();

        JOptionPane.showMessageDialog(this, "Thêm điểm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Add_GradeMouseClicked

    private void Delete_GradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_GradeMouseClicked
            try {
        int selectedRow = BANGDIEM.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn điểm cần xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String monHoc = BANGDIEM.getValueAt(selectedRow, 0).toString();
        String maSV = BANGDIEM.getValueAt(selectedRow, 3).toString();

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa điểm này? \n (Không thể hoàn tác)", 
                "Xóa điểm", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

            // Delete from table diem
            String deleteDiemQuery = "DELETE FROM diem WHERE MONHOC = ? AND MASV = ?";
            PreparedStatement pstDiem = con.prepareStatement(deleteDiemQuery);
            pstDiem.setString(1, monHoc);
            pstDiem.setString(2, maSV);
            pstDiem.executeUpdate();

            loadTableData_Grade();
            clearTxtFields_Grade();

            JOptionPane.showMessageDialog(this, "Xóa điểm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            con.close();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Delete_GradeMouseClicked

    private void Update_GradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_GradeMouseClicked
        try {
        int selectedRow = BANGDIEM.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn điểm cần cập nhật");
            return;
        }

        String monHoc = (String) BANGDIEM.getValueAt(selectedRow, 0); 
        String maSV = (String) BANGDIEM.getValueAt(selectedRow, 3); 

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

        String query = "UPDATE diem SET TINCHI = ?, DIEM = ? WHERE MONHOC = ? AND MASV = ?";
        PreparedStatement pst = con.prepareStatement(query);

        pst.setString(1, txtTinChi.getText());
        pst.setString(2, txtDiem.getText());
        pst.setString(3, monHoc);
        pst.setString(4, maSV);

        int rowsAffected = pst.executeUpdate();
        System.out.println("Rows affected: " + rowsAffected);

        if (rowsAffected > 0) {
            loadTableData_Grade();
            JOptionPane.showMessageDialog(this, "Cập nhật điểm thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu để cập nhật!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Update_GradeMouseClicked

    private void Search_GradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_GradeMouseClicked
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        String query = "SELECT * FROM diem WHERE MONHOC LIKE ?";
        PreparedStatement pst = con.prepareStatement(query);

        String searchMonHoc = "%" + txtMonHoc.getText().trim() + "%";
        pst.setString(1, searchMonHoc);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) BANGDIEM.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            Object[] row =  new Object[4];
            row[0] = rs.getString("MONHOC");
            row[1] = rs.getString("TINCHI");
            row[2] = rs.getString("DIEM");
            row[3] = rs.getString("MASV");

            model.addRow(row);
        }
        con.close();
    } catch(SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
    }//GEN-LAST:event_Search_GradeMouseClicked

    private void BANGLOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BANGLOPMouseClicked
                                
    try {
        int selectedRow = BANGLOP.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        // Get the selected class ID
        String classId = (String) BANGLOP.getValueAt(selectedRow, 0);
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");

        // Get class data
        String query = "SELECT * FROM lop WHERE MALOP = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, classId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            txtMaLopFK.setText(rs.getString("MALOP"));
            txtTenLop.setText(rs.getString("TENLOP"));
            txtKhoa.setText(rs.getString("KHOA"));
            txtChuyenNganh.setText(rs.getString("CHUYENNGANH"));
        }

        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BANGLOPMouseClicked
    }
    
    private void BANGDIEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BANGDIEMMouseClicked
    try {
        int selectedRow = BANGDIEM.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        // Get selected grade details
        String monHoc = (String) BANGDIEM.getValueAt(selectedRow, 0);
        String tinChi = (String) BANGDIEM.getValueAt(selectedRow, 1);
        String diem = (String) BANGDIEM.getValueAt(selectedRow, 2);
        String maSV = (String) BANGDIEM.getValueAt(selectedRow, 3);
        
        // Populate text fields with the selected grade details
        txtMonHoc.setText(monHoc);
        txtTinChi.setText(tinChi);
        txtDiem.setText(diem);
        txtMaSVFK.setText(maSV);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BANGDIEMMouseClicked
    
    
    private void loadTableData_Student() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
            String query = "SELECT * FROM sinhvien";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) BangSinhVien.getModel();
            model.setRowCount(0);
            
            while(rs.next()) {
                Object[] row = new Object[6];
                
                row[0] = rs.getString("MASV");
                row[1] = rs.getString("HOTEN");
                row[2] = rs.getString("NGAYSINH");
                row[3] = rs.getString("DIACHI");
                row[4] = rs.getString("EMAIL");
                row[5] = rs.getString("MALOP");
                
                model.addRow(row);
            }       
            
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }
    
    private void clearTxtFields_Student() {
        txtMaSV.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtMaLop.setText("");
    }

    private void loadTableData_Class() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        
        String query = "SELECT * FROM lop";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) BANGLOP.getModel();
        model.setRowCount(0); 
        
        while(rs.next()) {
            Object[] row = new Object[4];
            
            row[0] = rs.getString("MALOP");
            row[1] = rs.getString("TENLOP");
            row[2] = rs.getString("KHOA");
            row[3] = rs.getString("CHUYENNGANH");
            
            model.addRow(row);
        }       
        
        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
}
     
    private void clearTxtFields_Class() {
    txtMaLopFK.setText("");
    txtTenLop.setText("");
    txtKhoa.setText("");
    txtChuyenNganh.setText("");
    }
     
    private void loadTableData_Grade() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/student_management", "root", "");
        
        String query = "SELECT * FROM diem";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) BANGDIEM.getModel();
        model.setRowCount(0); 
        
    while(rs.next()) {
    String monHoc = rs.getString("MONHOC");
    int tinChi = rs.getInt("TINCHI");
    float diem = rs.getFloat("DIEM");
    String maSV = rs.getString("MASV");

    Object[] row = new Object[4];
    row[0] = monHoc;
    row[1] = String.valueOf(tinChi);
    row[2] = String.valueOf(diem);
    row[3] = maSV;

    model.addRow(row);
        }
  
        
        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
    }
}
     
    private void clearTxtFields_Grade() {
    txtMonHoc.setText("");
    txtTinChi.setText("");
    txtDiem.setText("");
    txtMaSVFK.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACCOUNTMANAGE;
    private javax.swing.JLabel Account_tittle;
    private javax.swing.JButton Add_Class;
    private javax.swing.JButton Add_Grade;
    private javax.swing.JButton Add_Student;
    private javax.swing.JTable BANGDIEM;
    private javax.swing.JTable BANGLOP;
    private javax.swing.JTable BangSinhVien;
    private javax.swing.JLabel CHUYENNGANH;
    private javax.swing.JPanel CLASSFICATION;
    private javax.swing.JLabel CLASSFICATION_menuslide1;
    private javax.swing.JPanel CLASSMANAGE;
    private javax.swing.JLabel CLASSMANAGE_menuslide;
    private javax.swing.JLabel CLASSMANAGE_tittle;
    private javax.swing.JLabel Classfication_title;
    private javax.swing.JLabel Closemenu;
    private javax.swing.JLabel DIACHI;
    private javax.swing.JLabel DIEM;
    private javax.swing.JButton Delete_Class;
    private javax.swing.JButton Delete_Grade;
    private javax.swing.JButton Delete_Student;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JPanel GRADEMANAGE;
    private javax.swing.JLabel GRADEMANAGE_menuslide;
    private javax.swing.JLabel GRADEMANAGE_tittle;
    private javax.swing.JPanel HOMEPAGE;
    private javax.swing.JLabel HOMEPAGE_menuslide;
    private javax.swing.JLabel HOTEN;
    private javax.swing.JLabel Homepage_tittle;
    private javax.swing.JLabel Icon_app;
    private javax.swing.JPanel Include_icon;
    private javax.swing.JLabel KHOA;
    private javax.swing.JLabel LOGOUT_menuslide;
    private javax.swing.JLabel MALOP;
    private javax.swing.JLabel MALOPFK;
    private javax.swing.JLabel MASV;
    private javax.swing.JLabel MONHOC;
    private javax.swing.JLabel MaSVFK;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel NGAYSINH;
    private javax.swing.JLabel OpenMenuicon;
    private javax.swing.JPanel PanelTotal;
    private javax.swing.JScrollPane SCROLLDIEM;
    private javax.swing.JScrollPane SCROLLLOP;
    private javax.swing.JLabel STUDENMANAGE_menuslide;
    private javax.swing.JScrollPane ScrollSinhVien;
    private javax.swing.JButton Search_Class;
    private javax.swing.JButton Search_Grade;
    private javax.swing.JButton Search_Student;
    private javax.swing.JSeparator Separator_Menuslide;
    private javax.swing.JPanel Slide_menu;
    private javax.swing.JLabel TENLOP;
    private javax.swing.JLabel TINCHI;
    private javax.swing.JPanel Tittle_font;
    private javax.swing.JButton Update_Class;
    private javax.swing.JButton Update_Grade;
    private javax.swing.JButton Update_Student;
    private javax.swing.JTextField txtChuyenNganh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaLopFK;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtMaSVFK;
    private javax.swing.JTextField txtMonHoc;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenLop;
    private javax.swing.JTextField txtTinChi;
    // End of variables declaration//GEN-END:variables
}


